# Generated by Django 6.1.2 on 2026-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coche', models.CharField(max_length=100, unique=True)),
                ('fecha_registrado', models.DateField()),
            ],
        ),
    ]
