# Generated by Django 6.1.2 on 2026-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='monto',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
