# Generated by Django 6.1.2 on 2026-10-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_reparacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
